eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    
    
server:
  port: 8010
spring:
  application:
    name: consumer-movie-ribbon

microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000
    
management:
  endpoint:
    health:
      show-details: always
      
