eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
e  
    
server:
  port: 8010
spring:
  application:
    name: consumer-movie-ribbon

microservice-provider-user:
  ribbon:
    listOfServers: localhost:8000
    
